# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/58/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/58/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amin/Desktop/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amin/Desktop/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/58/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/58/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amin/Desktop/project/CMakeFiles /home/amin/Desktop/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amin/Desktop/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/build
.PHONY : project/fast

src/AI.o: src/AI.c.o

.PHONY : src/AI.o

# target to build an object file
src/AI.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/AI.c.o
.PHONY : src/AI.c.o

src/AI.i: src/AI.c.i

.PHONY : src/AI.i

# target to preprocess a source file
src/AI.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/AI.c.i
.PHONY : src/AI.c.i

src/AI.s: src/AI.c.s

.PHONY : src/AI.s

# target to generate assembly for a file
src/AI.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/AI.c.s
.PHONY : src/AI.c.s

src/effects.o: src/effects.c.o

.PHONY : src/effects.o

# target to build an object file
src/effects.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/effects.c.o
.PHONY : src/effects.c.o

src/effects.i: src/effects.c.i

.PHONY : src/effects.i

# target to preprocess a source file
src/effects.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/effects.c.i
.PHONY : src/effects.c.i

src/effects.s: src/effects.c.s

.PHONY : src/effects.s

# target to generate assembly for a file
src/effects.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/effects.c.s
.PHONY : src/effects.c.s

src/init.o: src/init.c.o

.PHONY : src/init.o

# target to build an object file
src/init.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/init.c.o
.PHONY : src/init.c.o

src/init.i: src/init.c.i

.PHONY : src/init.i

# target to preprocess a source file
src/init.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/init.c.i
.PHONY : src/init.c.i

src/init.s: src/init.c.s

.PHONY : src/init.s

# target to generate assembly for a file
src/init.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/init.c.s
.PHONY : src/init.c.s

src/logic.o: src/logic.c.o

.PHONY : src/logic.o

# target to build an object file
src/logic.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/logic.c.o
.PHONY : src/logic.c.o

src/logic.i: src/logic.c.i

.PHONY : src/logic.i

# target to preprocess a source file
src/logic.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/logic.c.i
.PHONY : src/logic.c.i

src/logic.s: src/logic.c.s

.PHONY : src/logic.s

# target to generate assembly for a file
src/logic.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/logic.c.s
.PHONY : src/logic.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/main.c.s
.PHONY : src/main.c.s

src/physics.o: src/physics.c.o

.PHONY : src/physics.o

# target to build an object file
src/physics.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/physics.c.o
.PHONY : src/physics.c.o

src/physics.i: src/physics.c.i

.PHONY : src/physics.i

# target to preprocess a source file
src/physics.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/physics.c.i
.PHONY : src/physics.c.i

src/physics.s: src/physics.c.s

.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/physics.c.s
.PHONY : src/physics.c.s

src/simple_snake.o: src/simple_snake.c.o

.PHONY : src/simple_snake.o

# target to build an object file
src/simple_snake.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/simple_snake.c.o
.PHONY : src/simple_snake.c.o

src/simple_snake.i: src/simple_snake.c.i

.PHONY : src/simple_snake.i

# target to preprocess a source file
src/simple_snake.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/simple_snake.c.i
.PHONY : src/simple_snake.c.i

src/simple_snake.s: src/simple_snake.c.s

.PHONY : src/simple_snake.s

# target to generate assembly for a file
src/simple_snake.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/simple_snake.c.s
.PHONY : src/simple_snake.c.s

src/stack.o: src/stack.c.o

.PHONY : src/stack.o

# target to build an object file
src/stack.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/stack.c.o
.PHONY : src/stack.c.o

src/stack.i: src/stack.c.i

.PHONY : src/stack.i

# target to preprocess a source file
src/stack.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/stack.c.i
.PHONY : src/stack.c.i

src/stack.s: src/stack.c.s

.PHONY : src/stack.s

# target to generate assembly for a file
src/stack.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/stack.c.s
.PHONY : src/stack.c.s

src/view.o: src/view.c.o

.PHONY : src/view.o

# target to build an object file
src/view.c.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/view.c.o
.PHONY : src/view.c.o

src/view.i: src/view.c.i

.PHONY : src/view.i

# target to preprocess a source file
src/view.c.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/view.c.i
.PHONY : src/view.c.i

src/view.s: src/view.c.s

.PHONY : src/view.s

# target to generate assembly for a file
src/view.c.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/src/view.c.s
.PHONY : src/view.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... project"
	@echo "... edit_cache"
	@echo "... src/AI.o"
	@echo "... src/AI.i"
	@echo "... src/AI.s"
	@echo "... src/effects.o"
	@echo "... src/effects.i"
	@echo "... src/effects.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/logic.o"
	@echo "... src/logic.i"
	@echo "... src/logic.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/physics.o"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
	@echo "... src/simple_snake.o"
	@echo "... src/simple_snake.i"
	@echo "... src/simple_snake.s"
	@echo "... src/stack.o"
	@echo "... src/stack.i"
	@echo "... src/stack.s"
	@echo "... src/view.o"
	@echo "... src/view.i"
	@echo "... src/view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

